// swift-tools-version: 5.9
// SubHub iOS SDK 0.1.0 — binary distribution manifest (generated by build-xcframework.sh)

import PackageDescription

let package = Package(
    name: "SubHub",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(
            name: "SubHub",
            targets: ["SubHub"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "SubHub",
            url: "https://github.com/MoYoDream/subhub-ios-sdk/releases/download/0.1.0/SubHub.xcframework.zip",
            checksum: "54a7f7ba79171c8e9105fb30ed2e94feac81e1e84dff95a8c9db03c59dd67e89"
        ),
    ]
)
