// swift-tools-version: 5.9
// SubHub iOS SDK 0.3.1 — binary distribution manifest (generated by build-xcframework.sh)

import PackageDescription

let package = Package(
    name: "SubHub",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(
            name: "SubHub",
            targets: ["SubHub"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "SubHub",
            url: "https://github.com/MoYoDream/subhub-ios-sdk/releases/download/0.3.1/SubHub.xcframework.zip",
            checksum: "aa7e96ee1a40ae43ff474812867091f827e712397d7af6a6754d35e3392a877f"
        ),
    ]
)
