// swift-tools-version: 5.9
// SubHub iOS SDK 1.0.1 — binary distribution manifest (generated by build-xcframework.sh)

import PackageDescription

let package = Package(
    name: "SubHub",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(
            name: "SubHub",
            targets: ["SubHub"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "SubHub",
            url: "https://github.com/MoYoDream/subhub-ios-sdk/releases/download/1.0.1/SubHub.xcframework.zip",
            checksum: "cbccace351e8045b2b915c0398885a21645bc671d32ac98979da12e96a3693e2"
        ),
    ]
)
